[package]
name = "rust-learn"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "3"
tokio = { version = "1", features = ["full"] }
compose-rs = "0.0.3"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
mysql = "*"
lazy_static = "1.4"